import AppBar from '@/components/AppBar';
import AppFooter from '@/components/AppFooter';
import { useSettings } from '@/contexts/settings-context';
import { useEntries } from '@/hooks/useEntries';
import { useLevels } from '@/hooks/useLevels';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { Alert, Image, Linking, Modal, SafeAreaView, ScrollView, Share, StyleSheet, TouchableOpacity, View } from 'react-native';
import { Button, Card, Chip, IconButton, MD3DarkTheme, Provider as PaperProvider, ProgressBar, SegmentedButtons, Text, TextInput } from 'react-native-paper';

const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#bb86fc',
    background: '#0b0b0b',
    surface: '#1a1a1a',
    surfaceVariant: '#2a2a2a',
  },
};

interface Goals {
  dailyCalories: number;
  dailyProtein: number;
  dailyWater: number;
  weightGoal: 'lose' | 'maintain' | 'gain' | '';
  targetWeight: number;
}

interface DailyQuest {
  id: string;
  title: string;
  description: string;
  progress: number;
  target: number;
  points: number;
  completed: boolean;
  emoji: string;
}

export default function GoalsScreen() {
  const { accentColor, getFontSize, colors, theme } = useSettings();
  const { entries } = useEntries();
  const levelInfo = useLevels();
  const params = useLocalSearchParams();
  const [activeTab, setActiveTab] = useState<'goals' | 'quests' | 'planner'>('goals');
  const [mealPlan, setMealPlan] = useState<any>({});
  const [selectedRecipe, setSelectedRecipe] = useState<any>(null);
  const [showRecipeModal, setShowRecipeModal] = useState(false);
  const [showExportModal, setShowExportModal] = useState(false);
  const [checkedIngredients, setCheckedIngredients] = useState<Set<string>>(new Set());

  // Handle tab parameter from navigation
  useEffect(() => {
    if (params.tab === 'quests') {
      setActiveTab('quests');
    } else if (params.tab === 'planner') {
      setActiveTab('planner');
    }
  }, [params.tab]);
  const [goals, setGoals] = useState<Goals>({
    dailyCalories: 2000,
    dailyProtein: 150,
    dailyWater: 8,
    weightGoal: '',
    targetWeight: 0,
  });

  useEffect(() => {
    loadGoals();
    loadMealPlan();
  }, []);

  // Reload meal plan when switching to planner tab
  useEffect(() => {
    if (activeTab === 'planner') {
      loadMealPlan();
    }
  }, [activeTab]);

  async function loadGoals() {
    const saved = await AsyncStorage.getItem('humngry.goals');
    if (saved) {
      setGoals(JSON.parse(saved));
    }
  }

  async function loadMealPlan() {
    try {
      const saved = await AsyncStorage.getItem('humngry.mealPlan');
      if (saved) {
        setMealPlan(JSON.parse(saved));
      }
    } catch (error) {
      console.error('Error loading meal plan:', error);
    }
  }

  const openRecipe = (recipe: any) => {
    setSelectedRecipe(recipe);
    setShowRecipeModal(true);
  };

  const generateShoppingList = () => {
    const ingredients: { [key: string]: string[] } = {};
    
    // Collect all ingredients from all meals
    Object.values(mealPlan).forEach((dayMeals: any) => {
      Object.values(dayMeals).forEach((meal: any) => {
        if (meal.ingredients && Array.isArray(meal.ingredients)) {
          meal.ingredients.forEach((ing: any) => {
            const ingredient = ing.ingredient;
            const measure = ing.measure;
            if (!ingredients[ingredient]) {
              ingredients[ingredient] = [];
            }
            ingredients[ingredient].push(measure);
          });
        }
      });
    });

    return ingredients;
  };

  const formatShoppingListText = () => {
    const shoppingList = generateShoppingList();
    let listText = '🛒 Humngry Shopping List\n\n';
    Object.entries(shoppingList).forEach(([ingredient, measures]) => {
      listText += `• ${ingredient} - ${measures.join(', ')}\n`;
    });
    listText += '\n📱 Generated by Humngry';
    return listText;
  };

  const exportToApp = async (appType: 'share' | 'bring' | 'anylist' | 'ourgroceries') => {
    const shoppingList = generateShoppingList();
    
    if (Object.keys(shoppingList).length === 0) {
      Alert.alert('Empty Shopping List', 'Add meals to your plan first to generate a shopping list.');
      return;
    }

    if (appType === 'bring') {
      // Bring! deep link format - try multiple URL schemes
      const items = Object.keys(shoppingList).join(',');
      
      try {
        // Try opening directly (iOS/Android will handle if app is installed)
        const bringUrl = `bring://saveRecipe?source=humngry&ingredients=${encodeURIComponent(items)}`;
        await Linking.openURL(bringUrl);
        setShowExportModal(false);
      } catch (error) {
        // If it fails, offer to share instead
        Alert.alert(
          'Bring! Not Available',
          'Could not open Bring! app. Would you like to share the list another way?',
          [
            { text: 'Cancel', style: 'cancel' },
            { text: 'Share', onPress: () => exportToApp('share') }
          ]
        );
      }
    } else if (appType === 'anylist') {
      // AnyList deep link
      const items = Object.keys(shoppingList).map(item => `item=${encodeURIComponent(item)}`).join('&');
      
      try {
        const anylistUrl = `anylist://addItems?${items}`;
        await Linking.openURL(anylistUrl);
        setShowExportModal(false);
      } catch (error) {
        Alert.alert(
          'AnyList Not Available',
          'Could not open AnyList app. Would you like to share the list another way?',
          [
            { text: 'Cancel', style: 'cancel' },
            { text: 'Share', onPress: () => exportToApp('share') }
          ]
        );
      }
    } else if (appType === 'ourgroceries') {
      // OurGroceries deep link
      const items = Object.keys(shoppingList).join(',');
      
      try {
        const ourGroceriesUrl = `ourgroceries://addItems?items=${encodeURIComponent(items)}`;
        await Linking.openURL(ourGroceriesUrl);
        setShowExportModal(false);
      } catch (error) {
        Alert.alert(
          'OurGroceries Not Available',
          'Could not open OurGroceries app. Would you like to share the list another way?',
          [
            { text: 'Cancel', style: 'cancel' },
            { text: 'Share', onPress: () => exportToApp('share') }
          ]
        );
      }
    } else {
      // Generic share
      try {
        const result = await Share.share({
          message: formatShoppingListText(),
          title: 'Humngry Shopping List',
        });

        if (result.action === Share.sharedAction) {
          setShowExportModal(false);
        }
      } catch (error: any) {
        Alert.alert('Error', error.message);
      }
    }
  };

  const removeFromMealPlan = async (day: string, mealTime: string) => {
    try {
      const updatedPlan = { ...mealPlan };
      if (updatedPlan[day]) {
        delete updatedPlan[day][mealTime];
        if (Object.keys(updatedPlan[day]).length === 0) {
          delete updatedPlan[day];
        }
      }
      await AsyncStorage.setItem('humngry.mealPlan', JSON.stringify(updatedPlan));
      setMealPlan(updatedPlan);
    } catch (error) {
      console.error('Error removing from meal plan:', error);
    }
  };

  async function saveGoals(newGoals: Goals) {
    setGoals(newGoals);
    await AsyncStorage.setItem('humngry.goals', JSON.stringify(newGoals));
  }

  // Calculate today's progress
  const today = new Date().toDateString();
  const todayEntries = entries.filter(e => new Date(e.time).toDateString() === today);
  const todayCalories = todayEntries.reduce((sum, e) => sum + (e.calories || 0), 0);
  const todayProtein = todayEntries.reduce((sum, e) => sum + (e.protein || 0), 0);

  // Get water count
  const [waterCount, setWaterCount] = useState(0);
  useEffect(() => {
    async function loadWater() {
      const storedDate = await AsyncStorage.getItem('humngry.waterDate');
      const storedCount = await AsyncStorage.getItem('humngry.waterCount');
      if (storedDate === today && storedCount) {
        setWaterCount(parseInt(storedCount));
      }
    }
    loadWater();
  }, []);

  const calorieProgress = goals.dailyCalories > 0 ? Math.min(todayCalories / goals.dailyCalories, 1) : 0;
  const proteinProgress = goals.dailyProtein > 0 ? Math.min(todayProtein / goals.dailyProtein, 1) : 0;
  const waterProgress = goals.dailyWater > 0 ? Math.min(waterCount / goals.dailyWater, 1) : 0;

  // Daily Quests
  const dailyQuests: DailyQuest[] = [
    {
      id: 'log_meals',
      title: 'Log 3 Meals',
      description: 'Track your breakfast, lunch, and dinner',
      progress: todayEntries.length,
      target: 3,
      points: 30,
      completed: todayEntries.length >= 3,
      emoji: '🍽️',
    },
    {
      id: 'drink_water',
      title: 'Drink 8 Glasses',
      description: 'Stay hydrated throughout the day',
      progress: waterCount,
      target: 8,
      points: 20,
      completed: waterCount >= 8,
      emoji: '💧',
    },
    {
      id: 'hit_protein',
      title: 'Hit Protein Goal',
      description: `Reach ${goals.dailyProtein}g of protein`,
      progress: todayProtein,
      target: goals.dailyProtein,
      points: 25,
      completed: todayProtein >= goals.dailyProtein,
      emoji: '💪',
    },
    {
      id: 'stay_budget',
      title: 'Stay in Budget',
      description: 'Keep calories under your daily goal',
      progress: todayCalories,
      target: goals.dailyCalories,
      points: 35,
      completed: todayCalories <= goals.dailyCalories && todayCalories > 0,
      emoji: '🎯',
    },
  ];

  const totalQuestPoints = dailyQuests.reduce((sum, q) => sum + (q.completed ? q.points : 0), 0);
  const completedQuests = dailyQuests.filter(q => q.completed).length;

  return (
    <PaperProvider theme={darkTheme}>
      <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
        <ScrollView contentContainerStyle={styles.content}>
          <View style={styles.statusBarSpacer} />
          <View style={{ flexDirection: 'row', alignItems: 'flex-start' }}>
            <View style={{ flex: 1, maxWidth: '75%' }}>
              <Text style={[styles.title, { fontSize: getFontSize(28), color: colors.text }]}>🎯 Goals & Quests</Text>
              <Text style={[styles.screenDescription, { fontSize: getFontSize(14), color: colors.textSecondary }]}>
                Complete daily quests, track goals, and plan your meals.
              </Text>
            </View>
            <View style={{ width: 80 }} />
          </View>

          {/* Level System Card */}
          <Card style={[styles.levelCard, { borderColor: accentColor, borderWidth: 2 }]}>
            <Card.Content>
              <View style={styles.levelHeader}>
                <View>
                  <Text style={[styles.levelNumber, { fontSize: getFontSize(36), color: accentColor }]}>
                    Level {levelInfo.currentLevel}
                  </Text>
                  <Text style={[styles.levelTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                    {levelInfo.levelTitle}
                  </Text>
                </View>
                <View style={styles.levelBadge}>
                  <Text style={styles.levelBadgeEmoji}>
                    {levelInfo.currentLevel >= 15 ? '👑' : levelInfo.currentLevel >= 10 ? '⚡' : levelInfo.currentLevel >= 5 ? '🔥' : '⭐'}
                  </Text>
                </View>
              </View>

              <View style={styles.xpContainer}>
                <View style={styles.xpHeader}>
                  <Text style={[styles.xpLabel, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
                    Progress to {levelInfo.nextLevelTitle}
                  </Text>
                  <Text style={[styles.xpValue, { fontSize: getFontSize(13), color: accentColor }]}>
                    {Math.round(levelInfo.currentXP)} / {levelInfo.xpForNextLevel} XP
                  </Text>
                </View>
                <ProgressBar 
                  progress={levelInfo.xpProgress} 
                  color={accentColor} 
                  style={styles.xpProgressBar}
                />
              </View>

              {levelInfo.unlockedFeatures.length > 0 && (
                <View style={styles.unlockedFeatures}>
                  <Text style={[styles.unlockedTitle, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
                    🔓 Unlocked Features
                  </Text>
                  <View style={styles.featureChips}>
                    {levelInfo.unlockedFeatures.map((feature, index) => (
                      <Chip
                        key={index}
                        mode="flat"
                        style={[styles.featureChip, { backgroundColor: `${accentColor}22` }]}
                        textStyle={{ color: accentColor, fontSize: getFontSize(11) }}
                      >
                        {feature}
                      </Chip>
                    ))}
                  </View>
                </View>
              )}
            </Card.Content>
          </Card>

          {/* Tab Switcher */}
          <View style={styles.tabSwitcher}>
            <TouchableOpacity
              style={[styles.tab, activeTab === 'goals' && { ...styles.tabActive, borderBottomColor: accentColor }]}
              onPress={() => setActiveTab('goals')}
            >
              <Text style={[styles.tabText, { fontSize: getFontSize(15), color: activeTab === 'goals' ? accentColor : colors.textSecondary }]}>
                📊 Goals
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.tab, activeTab === 'quests' && { ...styles.tabActive, borderBottomColor: accentColor }]}
              onPress={() => setActiveTab('quests')}
            >
              <Text style={[styles.tabText, { fontSize: getFontSize(15), color: activeTab === 'quests' ? accentColor : colors.textSecondary }]}>
                🎮 Daily Quests
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.tab, activeTab === 'planner' && { ...styles.tabActive, borderBottomColor: accentColor }]}
              onPress={() => setActiveTab('planner')}
            >
              <Text style={[styles.tabText, { fontSize: getFontSize(15), color: activeTab === 'planner' ? accentColor : colors.textSecondary }]}>
                📅 Meal Plan
              </Text>
            </TouchableOpacity>
          </View>

          {activeTab === 'quests' && (
            <>
              {/* Quest Summary */}
              <Card style={[styles.card, { borderColor: accentColor, borderWidth: 2 }]}>
                <Card.Content>
                  <View style={styles.questSummary}>
                    <View>
                      <Text style={[styles.questSummaryTitle, { fontSize: getFontSize(20), color: colors.text }]}>
                        {completedQuests}/{dailyQuests.length} Completed
                      </Text>
                      <Text style={[styles.questSummarySubtitle, { fontSize: getFontSize(14), color: colors.textSecondary }]}>
                        🏆 {totalQuestPoints} points earned today
                      </Text>
                    </View>
                    <Text style={styles.questSummaryEmoji}>
                      {completedQuests === dailyQuests.length ? '🎉' : '⚔️'}
                    </Text>
                  </View>
                </Card.Content>
              </Card>

              {/* Daily Quests List */}
              {dailyQuests.map((quest) => (
                <Card key={quest.id} style={[styles.card, quest.completed && { borderColor: '#069420', borderWidth: 2 }]}>
                  <Card.Content>
                    <View style={styles.questCard}>
                      <View style={styles.questLeft}>
                        <Text style={styles.questEmoji}>{quest.emoji}</Text>
                        <View style={styles.questInfo}>
                          <Text style={[styles.questTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                            {quest.title}
                          </Text>
                          <Text style={[styles.questDescription, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
                            {quest.description}
                          </Text>
                          <View style={styles.questProgressContainer}>
                            <ProgressBar 
                              progress={Math.min(quest.progress / quest.target, 1)} 
                              color={quest.completed ? '#069420' : accentColor} 
                              style={styles.questProgressBar}
                            />
                            <Text style={[styles.questProgressText, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                              {Math.round(quest.progress)}/{quest.target}
                            </Text>
                          </View>
                        </View>
                      </View>
                      <View style={styles.questRight}>
                        {quest.completed ? (
                          <Text style={styles.questCompletedBadge}>✓</Text>
                        ) : (
                          <Text style={[styles.questPoints, { fontSize: getFontSize(14), color: accentColor }]}>
                            +{quest.points}
                          </Text>
                        )}
                      </View>
                    </View>
                  </Card.Content>
                </Card>
              ))}

              <Card style={[styles.card, { backgroundColor: colors.surfaceVariant }]}>
                <Card.Content>
                  <Text style={[styles.questTip, { fontSize: getFontSize(13), color: colors.text }]}>
                    💡 Complete all quests to earn bonus rewards and level up faster!
                  </Text>
                </Card.Content>
              </Card>
            </>
          )}

          {activeTab === 'goals' && (
            <>

          {/* Today's Progress */}
          <Card style={styles.card}>
            <Card.Title title="📊 Today's Progress" titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]} />
            <Card.Content>
              <View style={styles.progressItem}>
                <View style={styles.progressHeader}>
                  <Text style={[styles.progressLabel, { fontSize: getFontSize(15) }]}>🔥 Calories</Text>
                  <Text style={[styles.progressValue, { fontSize: getFontSize(15), color: accentColor }]}>
                    {Math.round(todayCalories)} / {goals.dailyCalories}
                  </Text>
                </View>
                <ProgressBar progress={calorieProgress} color={accentColor} style={styles.progressBar} />
              </View>

              <View style={styles.progressItem}>
                <View style={styles.progressHeader}>
                  <Text style={[styles.progressLabel, { fontSize: getFontSize(15) }]}>💪 Protein</Text>
                  <Text style={[styles.progressValue, { fontSize: getFontSize(15), color: accentColor }]}>
                    {Math.round(todayProtein)}g / {goals.dailyProtein}g
                  </Text>
                </View>
                <ProgressBar progress={proteinProgress} color={accentColor} style={styles.progressBar} />
              </View>

              <View style={styles.progressItem}>
                <View style={styles.progressHeader}>
                  <Text style={[styles.progressLabel, { fontSize: getFontSize(15) }]}>💧 Water</Text>
                  <Text style={[styles.progressValue, { fontSize: getFontSize(15), color: accentColor }]}>
                    {waterCount} / {goals.dailyWater} glasses
                  </Text>
                </View>
                <ProgressBar progress={waterProgress} color={accentColor} style={styles.progressBar} />
              </View>
            </Card.Content>
          </Card>

          {/* Daily Goals */}
          <Card style={styles.card}>
            <Card.Title title="🎯 Daily Goals" titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]} />
            <Card.Content>
              <View style={styles.inputGroup}>
                <Text style={[styles.inputLabel, { fontSize: getFontSize(15) }]}>Daily Calorie Goal</Text>
                <TextInput
                  mode="outlined"
                  value={String(goals.dailyCalories)}
                  onChangeText={(text) => saveGoals({ ...goals, dailyCalories: parseInt(text) || 0 })}
                  keyboardType="numeric"
                  style={styles.input}
                  outlineColor={accentColor}
                  activeOutlineColor={accentColor}
                  textColor="#fff"
                  right={<TextInput.Affix text="kcal" />}
                />
              </View>

              <View style={styles.inputGroup}>
                <Text style={[styles.inputLabel, { fontSize: getFontSize(15) }]}>Daily Protein Goal</Text>
                <TextInput
                  mode="outlined"
                  value={String(goals.dailyProtein)}
                  onChangeText={(text) => saveGoals({ ...goals, dailyProtein: parseInt(text) || 0 })}
                  keyboardType="numeric"
                  style={styles.input}
                  outlineColor={accentColor}
                  activeOutlineColor={accentColor}
                  textColor="#fff"
                  right={<TextInput.Affix text="g" />}
                />
              </View>

              <View style={styles.inputGroup}>
                <Text style={[styles.inputLabel, { fontSize: getFontSize(15) }]}>Daily Water Goal</Text>
                <TextInput
                  mode="outlined"
                  value={String(goals.dailyWater)}
                  onChangeText={(text) => saveGoals({ ...goals, dailyWater: parseInt(text) || 0 })}
                  keyboardType="numeric"
                  style={styles.input}
                  outlineColor={accentColor}
                  activeOutlineColor={accentColor}
                  textColor="#fff"
                  right={<TextInput.Affix text="glasses" />}
                />
              </View>
            </Card.Content>
          </Card>

          {/* Weight Goal */}
          <Card style={styles.card}>
            <Card.Title title="⚖️ Weight Goal" titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]} />
            <Card.Content>
              <Text style={[styles.helpText, { fontSize: getFontSize(13) }]}>
                What's your weight goal?
              </Text>
              <SegmentedButtons
                value={goals.weightGoal}
                onValueChange={(value) => saveGoals({ ...goals, weightGoal: value as any })}
                buttons={[
                  { value: 'lose', label: 'Lose' },
                  { value: 'maintain', label: 'Maintain' },
                  { value: 'gain', label: 'Gain' },
                ]}
                style={styles.segmented}
                theme={{ colors: { secondaryContainer: accentColor } }}
              />

              {goals.weightGoal && (
                <View style={styles.inputGroup}>
                  <Text style={[styles.inputLabel, { fontSize: getFontSize(15) }]}>Target Weight</Text>
                  <TextInput
                    mode="outlined"
                    value={goals.targetWeight ? String(goals.targetWeight) : ''}
                    onChangeText={(text) => saveGoals({ ...goals, targetWeight: parseFloat(text) || 0 })}
                    keyboardType="decimal-pad"
                    style={styles.input}
                    outlineColor={accentColor}
                    activeOutlineColor={accentColor}
                    textColor="#fff"
                    right={<TextInput.Affix text="kg" />}
                    placeholder="Enter target weight"
                  />
                </View>
              )}
            </Card.Content>
          </Card>

          {/* Tips */}
          <Card style={[styles.tipCard, { borderLeftColor: accentColor }]}>
            <Card.Content>
              <Text style={[styles.tipText, { fontSize: getFontSize(14) }]}>
                💡 Tip: Adjust your goals as you progress. Small, consistent changes lead to lasting results!
              </Text>
            </Card.Content>
          </Card>
            </>
          )}

          {activeTab === 'planner' && (
            <>
              <Card style={styles.card}>
                <Card.Title title="📅 Weekly Meal Planner" titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]} />
                <Card.Content>
                  <View style={[styles.tipCard, { backgroundColor: colors.surfaceVariant, borderLeftColor: accentColor }]}>
                    <Text style={[styles.tipText, { fontSize: getFontSize(13), color: colors.text }]}>
                      💡 <Text style={{ fontWeight: '700' }}>How to use:</Text>{'\n'}
                      1️⃣ Go to <Text style={{ fontWeight: '700', color: accentColor }}>Recipes</Text> tab and find a recipe you like{'\n'}
                      2️⃣ Tap <Text style={{ fontWeight: '700', color: accentColor }}>"View Recipe"</Text> to see details{'\n'}
                      3️⃣ Click <Text style={{ fontWeight: '700', color: accentColor }}>"Add to Meal Plan"</Text> button{'\n'}
                      4️⃣ Choose which day and meal time{'\n'}
                      5️⃣ Your meal will appear here with all ingredients!
                    </Text>
                  </View>
                  
                  {/* Week Days */}
                  {['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day, index) => {
                    const dayMeals = mealPlan[day] || {};
                    return (
                      <View
                        key={day}
                        style={[styles.dayCard, { backgroundColor: colors.surfaceVariant, borderColor: colors.border }]}
                      >
                        <Text style={[styles.dayName, { fontSize: getFontSize(16), color: colors.text, marginBottom: 12 }]}>
                          {day}
                        </Text>
                        <View style={styles.mealSlots}>
                          {/* Breakfast */}
                          <View style={[styles.mealSlot, { backgroundColor: colors.surface, borderColor: colors.border }]}>
                            <TouchableOpacity
                              style={{ flex: 1, width: '100%', alignItems: 'center' }}
                              onPress={() => dayMeals.breakfast && openRecipe(dayMeals.breakfast)}
                              disabled={!dayMeals.breakfast}
                              activeOpacity={0.7}
                            >
                              <Text style={[styles.mealSlotLabel, { fontSize: getFontSize(11), color: colors.textSecondary }]}>
                                🌅 Breakfast
                              </Text>
                              {dayMeals.breakfast ? (
                                <Text style={[styles.mealName, { fontSize: getFontSize(10), color: colors.text }]} numberOfLines={2}>
                                  {dayMeals.breakfast.name}
                                </Text>
                              ) : (
                                <Text style={[styles.emptySlot, { fontSize: getFontSize(10), color: colors.textTertiary }]}>
                                  Empty
                                </Text>
                              )}
                            </TouchableOpacity>
                            {dayMeals.breakfast && (
                              <IconButton
                                icon="close-circle"
                                size={16}
                                iconColor="#ff4444"
                                style={{ position: 'absolute', top: -8, right: -8, margin: 0 }}
                                onPress={() => removeFromMealPlan(day, 'breakfast')}
                              />
                            )}
                          </View>

                          {/* Lunch */}
                          <View style={[styles.mealSlot, { backgroundColor: colors.surface, borderColor: colors.border }]}>
                            <TouchableOpacity
                              style={{ flex: 1, width: '100%', alignItems: 'center' }}
                              onPress={() => dayMeals.lunch && openRecipe(dayMeals.lunch)}
                              disabled={!dayMeals.lunch}
                              activeOpacity={0.7}
                            >
                              <Text style={[styles.mealSlotLabel, { fontSize: getFontSize(11), color: colors.textSecondary }]}>
                                ☀️ Lunch
                              </Text>
                              {dayMeals.lunch ? (
                                <Text style={[styles.mealName, { fontSize: getFontSize(10), color: colors.text }]} numberOfLines={2}>
                                  {dayMeals.lunch.name}
                                </Text>
                              ) : (
                                <Text style={[styles.emptySlot, { fontSize: getFontSize(10), color: colors.textTertiary }]}>
                                  Empty
                                </Text>
                              )}
                            </TouchableOpacity>
                            {dayMeals.lunch && (
                              <IconButton
                                icon="close-circle"
                                size={16}
                                iconColor="#ff4444"
                                style={{ position: 'absolute', top: -8, right: -8, margin: 0 }}
                                onPress={() => removeFromMealPlan(day, 'lunch')}
                              />
                            )}
                          </View>

                          {/* Dinner */}
                          <View style={[styles.mealSlot, { backgroundColor: colors.surface, borderColor: colors.border }]}>
                            <TouchableOpacity
                              style={{ flex: 1, width: '100%', alignItems: 'center' }}
                              onPress={() => dayMeals.dinner && openRecipe(dayMeals.dinner)}
                              disabled={!dayMeals.dinner}
                              activeOpacity={0.7}
                            >
                              <Text style={[styles.mealSlotLabel, { fontSize: getFontSize(11), color: colors.textSecondary }]}>
                                🌙 Dinner
                              </Text>
                              {dayMeals.dinner ? (
                                <Text style={[styles.mealName, { fontSize: getFontSize(10), color: colors.text }]} numberOfLines={2}>
                                  {dayMeals.dinner.name}
                                </Text>
                              ) : (
                                <Text style={[styles.emptySlot, { fontSize: getFontSize(10), color: colors.textTertiary }]}>
                                  Empty
                                </Text>
                              )}
                            </TouchableOpacity>
                            {dayMeals.dinner && (
                              <IconButton
                                icon="close-circle"
                                size={16}
                                iconColor="#ff4444"
                                style={{ position: 'absolute', top: -8, right: -8, margin: 0 }}
                                onPress={() => removeFromMealPlan(day, 'dinner')}
                              />
                            )}
                          </View>
                        </View>
                      </View>
                    );
                  })}
                </Card.Content>
              </Card>

              {/* Shopping List */}
              <Card style={styles.card}>
                <Card.Title 
                  title="🛒 Shopping List" 
                  titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]}
                />
                <Card.Content>
                  {Object.keys(mealPlan).length > 0 ? (
                    <>
                      <Text style={[styles.helpText, { fontSize: getFontSize(13), color: colors.textSecondary, marginBottom: 12 }]}>
                        Ingredients from your meal plan:
                      </Text>
                      <ScrollView 
                        style={{ maxHeight: 300 }}
                        nestedScrollEnabled={true}
                        showsVerticalScrollIndicator={true}
                      >
                        {Object.entries(generateShoppingList()).map(([ingredient, measures], idx) => {
                          const isChecked = checkedIngredients.has(ingredient);
                          return (
                            <TouchableOpacity
                              key={idx}
                              style={[
                                styles.shoppingItem, 
                                { 
                                  backgroundColor: isChecked ? `${accentColor}22` : colors.surfaceVariant, 
                                  borderColor: isChecked ? accentColor : colors.border,
                                  opacity: isChecked ? 0.7 : 1,
                                }
                              ]}
                              onPress={() => {
                                const newChecked = new Set(checkedIngredients);
                                if (isChecked) {
                                  newChecked.delete(ingredient);
                                } else {
                                  newChecked.add(ingredient);
                                }
                                setCheckedIngredients(newChecked);
                              }}
                              activeOpacity={0.7}
                            >
                              <View style={{ flexDirection: 'row', alignItems: 'center', flex: 1 }}>
                                <Text style={{ fontSize: getFontSize(18), marginRight: 8 }}>
                                  {isChecked ? '✅' : '⬜'}
                                </Text>
                                <View style={{ flex: 1 }}>
                                  <Text style={[
                                    styles.shoppingIngredient, 
                                    { 
                                      fontSize: getFontSize(14), 
                                      color: colors.text,
                                      textDecorationLine: isChecked ? 'line-through' : 'none',
                                    }
                                  ]}>
                                    {ingredient}
                                  </Text>
                                  <Text style={[styles.shoppingMeasure, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                                    {measures.join(', ')}
                                  </Text>
                                </View>
                              </View>
                            </TouchableOpacity>
                          );
                        })}
                      </ScrollView>

                      {/* Action Buttons */}
                      <View style={{ flexDirection: 'row', gap: 8, marginTop: 16 }}>
                        <Button
                          mode="contained"
                          onPress={() => setShowExportModal(true)}
                          style={[styles.exportButton, { flex: 1 }]}
                          buttonColor={accentColor}
                          icon="export-variant"
                          labelStyle={{ fontSize: getFontSize(14), fontWeight: '700' }}
                        >
                          Export
                        </Button>
                        {checkedIngredients.size > 0 && (
                          <Button
                            mode="outlined"
                            onPress={() => setCheckedIngredients(new Set())}
                            style={{ flex: 1 }}
                            textColor={accentColor}
                            labelStyle={{ fontSize: getFontSize(14) }}
                          >
                            Clear ({checkedIngredients.size})
                          </Button>
                        )}
                      </View>
                    </>
                  ) : (
                    <Text style={[styles.helpText, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
                      Add meals to your plan to see ingredients here.
                    </Text>
                  )}
                </Card.Content>
              </Card>

              {/* Meal Prep Tracker */}
              <Card style={styles.card}>
                <Card.Title title="👨‍🍳 Meal Prep Tracker" titleStyle={[styles.cardTitle, { fontSize: getFontSize(18) }]} />
                <Card.Content>
                  <Text style={[styles.helpText, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
                    Track batch cooking and meal prep sessions.
                  </Text>
                  <View style={styles.prepStats}>
                    <View style={styles.prepStatItem}>
                      <Text style={[styles.prepStatValue, { fontSize: getFontSize(24), color: accentColor }]}>0</Text>
                      <Text style={[styles.prepStatLabel, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                        Meals Prepped
                      </Text>
                    </View>
                    <View style={styles.prepStatItem}>
                      <Text style={[styles.prepStatValue, { fontSize: getFontSize(24), color: accentColor }]}>0</Text>
                      <Text style={[styles.prepStatLabel, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                        This Week
                      </Text>
                    </View>
                  </View>
                </Card.Content>
              </Card>
            </>
          )}
        </ScrollView>
      </SafeAreaView>
      <AppBar />
      <AppFooter />

      {/* Recipe Detail Modal */}
      <Modal
        visible={showRecipeModal}
        onRequestClose={() => setShowRecipeModal(false)}
        animationType="slide"
        transparent={false}
      >
        <SafeAreaView style={[styles.modalContainer, { backgroundColor: colors.background }]}>
          <View style={[styles.modalHeader, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}>
            <IconButton
              icon="close"
              iconColor={colors.text}
              size={28}
              onPress={() => setShowRecipeModal(false)}
            />
            <Text style={[styles.modalTitle, { color: colors.text, fontSize: getFontSize(18) }]} numberOfLines={2}>
              {selectedRecipe?.name}
            </Text>
            <View style={{ width: 40 }} />
          </View>

          <ScrollView contentContainerStyle={styles.modalContent}>
            {selectedRecipe?.thumbnail && (
              <Image
                source={{ uri: selectedRecipe.thumbnail }}
                style={styles.modalImage}
                resizeMode="cover"
              />
            )}

            <View style={styles.modalInfo}>
              {selectedRecipe?.category && (
                <Chip
                  icon="tag"
                  style={[styles.modalChip, { backgroundColor: colors.surface }]}
                  textStyle={[styles.modalChipText, { color: colors.text, fontSize: getFontSize(13) }]}
                >
                  {selectedRecipe.category}
                </Chip>
              )}
              {selectedRecipe?.area && (
                <Chip
                  icon="earth"
                  style={[styles.modalChip, { backgroundColor: colors.surface }]}
                  textStyle={[styles.modalChipText, { color: colors.text, fontSize: getFontSize(13) }]}
                >
                  {selectedRecipe.area}
                </Chip>
              )}
            </View>

            {selectedRecipe?.ingredients && selectedRecipe.ingredients.length > 0 && (
              <View style={styles.section}>
                <Text style={[styles.sectionTitle, { fontSize: getFontSize(18), color: colors.text }]}>🥘 Ingredients</Text>
                <View style={styles.ingredientsList}>
                  {selectedRecipe.ingredients.map((ing: any, idx: number) => (
                    <View key={idx} style={styles.ingredientItem}>
                      <Text style={[styles.ingredientBullet, { color: accentColor }]}>•</Text>
                      <Text style={[styles.ingredientText, { fontSize: getFontSize(15), color: colors.textSecondary }]}>
                        {ing.measure} {ing.ingredient}
                      </Text>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {selectedRecipe?.instructions && (
              <View style={styles.section}>
                <Text style={[styles.sectionTitle, { fontSize: getFontSize(18), color: colors.text }]}>👨‍🍳 Instructions</Text>
                <View style={styles.instructionsList}>
                  {selectedRecipe.instructions
                    .split(/\r?\n/)
                    .filter((step: string) => step.trim().length > 0)
                    .filter((step: string) => !/^\d+$/.test(step.trim()))
                    .filter((step: string) => !/^step\s+\d+$/i.test(step.trim()))
                    .map((step: string, idx: number) => (
                      <View key={idx} style={styles.instructionStep}>
                        <View style={[styles.stepNumber, { backgroundColor: accentColor }]}>
                          <Text style={[styles.stepNumberText, { fontSize: getFontSize(16), color: theme === 'dark' ? '#000' : '#fff' }]}>{idx + 1}</Text>
                        </View>
                        <Text style={[styles.instructionText, { fontSize: getFontSize(15), color: colors.textSecondary }]}>{step.trim()}</Text>
                      </View>
                    ))}
                </View>
              </View>
            )}

            {selectedRecipe?.youtubeUrl && (
              <Button
                mode="contained"
                onPress={() => selectedRecipe && Linking.openURL(selectedRecipe.youtubeUrl)}
                style={styles.youtubeButton}
                buttonColor="#ff0000"
                icon="youtube"
                labelStyle={{ fontSize: getFontSize(15), fontWeight: '700' }}
                textColor='#ffffff'
              >
                📺 Watch Video Tutorial
              </Button>
            )}
          </ScrollView>
        </SafeAreaView>
      </Modal>

      {/* Export Shopping List Modal */}
      <Modal
        visible={showExportModal}
        onRequestClose={() => setShowExportModal(false)}
        animationType="slide"
        transparent={true}
      >
        <View style={styles.exportModalOverlay}>
          <View style={[styles.exportModalContent, { backgroundColor: colors.surface, borderColor: accentColor }]}>
            <View style={styles.exportModalHeader}>
              <Text style={[styles.exportModalTitle, { fontSize: getFontSize(20), color: colors.text }]}>
                Export Shopping List
              </Text>
              <IconButton
                icon="close"
                iconColor={colors.textSecondary}
                size={24}
                onPress={() => setShowExportModal(false)}
                style={{ margin: 0 }}
              />
            </View>

            <Text style={[styles.exportModalSubtitle, { fontSize: getFontSize(13), color: colors.textSecondary }]}>
              Choose where to export your shopping list:
            </Text>

            <View style={styles.exportOptions}>
              {/* Bring! */}
              <TouchableOpacity
                style={[styles.exportOption, { backgroundColor: colors.background, borderColor: colors.border }]}
                onPress={() => exportToApp('bring')}
                activeOpacity={0.7}
              >
                <View style={[styles.exportIconContainer, { backgroundColor: '#4FABA2' }]}>
                  <Text style={styles.exportIcon}>🛒</Text>
                </View>
                <View style={styles.exportOptionText}>
                  <Text style={[styles.exportOptionTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                    Bring! Shopping List
                  </Text>
                  <Text style={[styles.exportOptionSubtitle, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                    Popular shopping list app
                  </Text>
                </View>
                <IconButton icon="chevron-right" iconColor={colors.textTertiary} size={20} style={{ margin: 0 }} />
              </TouchableOpacity>

              {/* AnyList */}
              <TouchableOpacity
                style={[styles.exportOption, { backgroundColor: colors.background, borderColor: colors.border }]}
                onPress={() => exportToApp('anylist')}
                activeOpacity={0.7}
              >
                <View style={[styles.exportIconContainer, { backgroundColor: '#FF6B35' }]}>
                  <Text style={styles.exportIcon}>📝</Text>
                </View>
                <View style={styles.exportOptionText}>
                  <Text style={[styles.exportOptionTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                    AnyList
                  </Text>
                  <Text style={[styles.exportOptionSubtitle, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                    Recipe organizer & lists
                  </Text>
                </View>
                <IconButton icon="chevron-right" iconColor={colors.textTertiary} size={20} style={{ margin: 0 }} />
              </TouchableOpacity>

              {/* OurGroceries */}
              <TouchableOpacity
                style={[styles.exportOption, { backgroundColor: colors.background, borderColor: colors.border }]}
                onPress={() => exportToApp('ourgroceries')}
                activeOpacity={0.7}
              >
                <View style={[styles.exportIconContainer, { backgroundColor: '#5CB85C' }]}>
                  <Text style={styles.exportIcon}>🥬</Text>
                </View>
                <View style={styles.exportOptionText}>
                  <Text style={[styles.exportOptionTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                    OurGroceries
                  </Text>
                  <Text style={[styles.exportOptionSubtitle, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                    Shared grocery lists
                  </Text>
                </View>
                <IconButton icon="chevron-right" iconColor={colors.textTertiary} size={20} style={{ margin: 0 }} />
              </TouchableOpacity>

              {/* Generic Share */}
              <TouchableOpacity
                style={[styles.exportOption, { backgroundColor: colors.background, borderColor: colors.border }]}
                onPress={() => exportToApp('share')}
                activeOpacity={0.7}
              >
                <View style={[styles.exportIconContainer, { backgroundColor: accentColor }]}>
                  <Text style={styles.exportIcon}>📤</Text>
                </View>
                <View style={styles.exportOptionText}>
                  <Text style={[styles.exportOptionTitle, { fontSize: getFontSize(16), color: colors.text }]}>
                    Share or Copy
                  </Text>
                  <Text style={[styles.exportOptionSubtitle, { fontSize: getFontSize(12), color: colors.textSecondary }]}>
                    Share to any app or copy text
                  </Text>
                </View>
                <IconButton icon="chevron-right" iconColor={colors.textTertiary} size={20} style={{ margin: 0 }} />
              </TouchableOpacity>
            </View>

            <Text style={[styles.exportModalHint, { fontSize: getFontSize(11), color: colors.textTertiary }]}>
              💡 If an app isn't installed, you'll be able to share as text instead
            </Text>
          </View>
        </View>
      </Modal>
    </PaperProvider>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { padding: 16, paddingTop: 125, paddingBottom: 60 },
  statusBarSpacer: { height: 24 },
  title: { fontSize: 28, fontWeight: '800', marginBottom: 12, letterSpacing: -0.5 },
  screenDescription: { fontSize: 14, lineHeight: 20, marginBottom: 16 },
  levelCard: {
    marginBottom: 16,
    borderRadius: 16,
    elevation: 6,
  },
  levelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  levelNumber: {
    fontWeight: '900',
    letterSpacing: -1,
    marginBottom: 4,
  },
  levelTitle: {
    fontWeight: '700',
  },
  levelBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#2a2a2a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  levelBadgeEmoji: {
    fontSize: 32,
  },
  xpContainer: {
    marginBottom: 12,
  },
  xpHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  xpLabel: {
    fontWeight: '600',
  },
  xpValue: {
    fontWeight: '800',
  },
  xpProgressBar: {
    height: 10,
    borderRadius: 5,
  },
  unlockedFeatures: {
    marginTop: 12,
  },
  unlockedTitle: {
    fontWeight: '700',
    marginBottom: 8,
  },
  featureChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  featureChip: {
    height: 30,
    paddingVertical: 2,
  },
  tabSwitcher: {
    flexDirection: 'row',
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#2a2a2a',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tabActive: {
    borderBottomWidth: 3,
  },
  tabText: {
    fontWeight: '700',
  },
  card: { marginBottom: 16, borderRadius: 12, elevation: 4 },
  cardTitle: { fontSize: 18, fontWeight: '700' },
  questSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  questSummaryTitle: {
    fontWeight: '800',
    marginBottom: 4,
  },
  questSummarySubtitle: {
    fontWeight: '600',
  },
  questSummaryEmoji: {
    fontSize: 48,
  },
  questCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  questLeft: {
    flexDirection: 'row',
    flex: 1,
    gap: 12,
  },
  questEmoji: {
    fontSize: 32,
  },
  questInfo: {
    flex: 1,
  },
  questTitle: {
    fontWeight: '700',
    marginBottom: 4,
  },
  questDescription: {
    marginBottom: 8,
    lineHeight: 18,
  },
  questProgressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  questProgressBar: {
    flex: 1,
    height: 8,
    borderRadius: 4,
  },
  questProgressText: {
    fontWeight: '600',
    minWidth: 50,
    textAlign: 'right',
  },
  questRight: {
    alignItems: 'center',
    marginLeft: 12,
  },
  questCompletedBadge: {
    fontSize: 32,
    color: '#069420',
  },
  questPoints: {
    fontWeight: '800',
  },
  questTip: {
    lineHeight: 20,
    fontStyle: 'italic',
  },
  progressItem: { marginBottom: 20 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  progressLabel: { color: '#ddd', fontSize: 15, fontWeight: '600' },
  progressValue: { fontSize: 15, fontWeight: '700' },
  progressBar: { height: 8, borderRadius: 4 },
  inputGroup: { marginBottom: 16 },
  inputLabel: { color: '#ddd', fontSize: 15, fontWeight: '600', marginBottom: 8 },
  input: { backgroundColor: '#0b0b0b' },
  helpText: { color: '#aaa', fontSize: 13, marginBottom: 12, lineHeight: 20 },
  segmented: { marginBottom: 16 },
  tipCard: { backgroundColor: '#1e1e1e', borderLeftWidth: 4, borderRadius: 12 },
  tipText: { color: '#ddd', fontSize: 14, lineHeight: 22 },
  comingSoonFeatures: {
    gap: 8,
    marginTop: 12,
  },
  featureText: {
    lineHeight: 24,
    fontWeight: '600',
  },
  dayCard: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  dayName: {
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  mealSlots: {
    flexDirection: 'row',
    gap: 10,
  },
  mealSlot: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    minHeight: 60,
    justifyContent: 'center',
    borderWidth: 1,
  },
  mealSlotLabel: {
    fontWeight: '600',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptySlot: {
    opacity: 0.5,
    textAlign: 'center',
  },
  mealName: {
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 14,
  },
  prepStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 16,
  },
  prepStatItem: {
    alignItems: 'center',
  },
  prepStatValue: {
    fontWeight: '700',
    marginBottom: 4,
  },
  prepStatLabel: {
    textAlign: 'center',
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    elevation: 4,
  },
  modalTitle: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '700',
    marginHorizontal: 8,
  },
  modalContent: {
    paddingBottom: 32,
  },
  modalImage: {
    width: '100%',
    height: 250,
  },
  modalInfo: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 16,
  },
  modalChip: {
    elevation: 2,
  },
  modalChipText: {
    fontWeight: '600',
  },
  section: {
    padding: 16,
    marginBottom: 8,
  },
  sectionTitle: {
    fontWeight: '700',
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  ingredientsList: {
    gap: 10,
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  ingredientBullet: {
    fontSize: 20,
    marginRight: 12,
    marginTop: -2,
  },
  ingredientText: {
    flex: 1,
    lineHeight: 22,
  },
  instructionsList: {
    gap: 16,
  },
  instructionStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  stepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  stepNumberText: {
    fontWeight: '700',
  },
  instructionText: {
    flex: 1,
    lineHeight: 24,
  },
  youtubeButton: {
    marginHorizontal: 16,
    marginTop: 16,
  },
  shoppingItem: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
  },
  shoppingIngredient: {
    fontWeight: '600',
    marginBottom: 4,
  },
  shoppingMeasure: {
    fontStyle: 'italic',
    paddingLeft: 12,
  },
  exportButton: {
    borderRadius: 8,
    paddingVertical: 4,
  },
  exportModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  exportModalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 3,
    padding: 24,
    paddingBottom: 40,
  },
  exportModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  exportModalTitle: {
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  exportModalSubtitle: {
    marginBottom: 20,
    lineHeight: 18,
  },
  exportOptions: {
    gap: 12,
    marginBottom: 16,
  },
  exportOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
  },
  exportIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportIcon: {
    fontSize: 24,
  },
  exportOptionText: {
    flex: 1,
  },
  exportOptionTitle: {
    fontWeight: '700',
    marginBottom: 2,
  },
  exportOptionSubtitle: {
    lineHeight: 16,
  },
  exportModalHint: {
    fontStyle: 'italic',
    lineHeight: 16,
    textAlign: 'center',
  },
});
